### ISSUE TITLE
Hand Tracking is not working properly  

### ISSUE THREAD

**Issue by shahanawazkhan0408** [jcmellado/js-handtracking#3]
![image]
(https://cloud.githubusercontent.com/assets/14199026/9762276/10cb3126-5720-11e5-9ae5-706a537d5c81.png)

Hand Tracking is not clear please try to fix the issue and update the new source code.

and also tell me the where i need to change the values so that it ll work properly.

**Comment by jcmellado** [comment]
The code is working fine, the poor detection is due the basic approach used for the skin detection phase. It's explained in the main page of the project: https://github.com/jcmellado/js-handtracking

**Comment by shahanawazkhan0408** [comment]
Thanks a lot, will you help me in the detection of palm detection??

if possible try t help me.
i have attached image, like that i need final output.

thanks and regards ,
shanawaz
