### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by ddanielhpf** [jcmellado/js-handtracking#8]
Hi, I wanted to test the program but when I run it it only gives a white screen, could you help me?

![image](https://user-images.githubusercontent.com/24281146/55787432-9ef09900-5a8c-11e9-903d-1803f0592194.png)

**Comment by jcmellado** [comment]
Error:
```
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at DEMO.videoReady (demo.html:44)
    at demo.html:37
```
Browsers removed the `createObjectURL` method, but the demo is very old (2013) and it is still using that method.

**Comment by jcmellado** [comment]
I have update the demo, it must be working again now.

**Comment by ddanielhpf** [comment]
thank you
